services:
  - type: web
    name: mnist-digit-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PORT
        value: 10000
